part of "_.dart";

enum CHAR__ASCII /*
  web://org.wikipedia/ASCII */ {
  null___in_visible(empty___string) /* "NIL", "^@" */,
  start_of_heading___in_visible(empty___string) /* "SOH", "^A" */,
  start_of_text___in_visible(empty___string) /* "STX", "^B" */,
  end_of_text___in_visible(empty___string) /* "ETX", "^C" */,
  end_of_transmission___in_visible(empty___string) /* "EOT", "^D" */,
  enquiry___in_visible(empty___string) /* "ENQ", "^E" */,
  acknowledgement___in_visible(empty___string) /* "ACK", "^F" */,
  bell___in_visible(empty___string) /* "BEL", "^G" */,
  backspace___in_visible(empty___string) /* "BS", "^H" */,
  horizontal_tab___in_visible(empty___string) /* "HT", "^I" */,
  //
  line_feed___in_visible(chars__line_feed___string) /* "LF", "^J" */,
  //
  vertical_tab___in_visible(empty___string) /* "VT", "^K" */,
  form_feed___in_visible(empty___string) /* "FF", "^L" */,
  carriage_return___in_visible(empty___string) /* "CR", "^M" */,
  shift_out___in_visible(empty___string) /* "SO", "^N" */,
  shift_in___in_visible(empty___string) /* "SI", "^O" */,
  data_link_escape___in_visible(empty___string) /* "DLE", "^P" */,
  device_control_one___in_visible(empty___string) /* "DC1", "^Q" */,
  device_control_two___in_visible(empty___string) /* "DC2", "^R" */,
  device_control_three___in_visible(empty___string) /* "DC3", "^S" */,
  device_control_four___in_visible(empty___string) /* "DC4", "^T" */,
  negative_acknowledgement___in_visible(empty___string) /* "NAK", "^U" */,
  synchronous_idle___in_visible(empty___string) /* "SYN", "^V" */,
  end_of_transmission_block___in_visible(empty___string) /* "ETB", "^W" */,
  cancel___in_visible(empty___string) /* "CAN", "^X" */,
  end_of_medium___in_visible(empty___string) /* "EM", "^Y" */,
  substitute___in_visible(empty___string) /* "SUB", "^Z" */,
  escape___in_visible(empty___string) /* "ESC", "^[" */,
  file_separator___in_visible(empty___string) /* "FS", "^\" */,
  group_separator___in_visible(empty___string) /* "GS", "^]" */,
  record_separator___in_visible(empty___string) /* "RS", "^^" */,
  unit_separator___in_visible(empty___string) /* "US", "^_" */,
  //
  space(chars__space___string),
  exclamation(chars__exclamation___string),
  quote__double(chars__quote__double___string),
  hash(chars__hash___string),
  dollar(chars__dollar___string),
  percent(chars__percent___string),
  ampersand(chars__ampersand___string),
  quote__single(chars__quote__single___string),
  bracket__round__open(chars__bracket__round__open___string),
  bracket__round__close(chars__bracket__round__close___string),
  asterisk(chars__asterisk___string),
  plus(chars__plus___string),
  comma(chars__comma___string),
  dash(chars__dash___string),
  dot(chars__dot___string),
  slash__forward(chars__slash__forward___string),
  //
  number__zero(chars__number__zero___string),
  number__one(chars__number__one___string),
  number__two(chars__number__two___string),
  number__three(chars__number__three___string),
  number__four(chars__number__four___string),
  number__five(chars__number__five___string),
  number__six(chars__number__six___string),
  number__seven(chars__number__seven___string),
  number__eight(chars__number__eight___string),
  number__nine(chars__number__nine___string),
  //
  colon(chars__colon___string),
  colon__semi(chars__colon__semi___string),
  bracket__angle__open(chars__less_than___string),
  equal(chars__equal___string),
  bracket__angle__close(chars__more_than___string),
  question(chars__question___string),
  at(chars__at___string),
  //
  alphabet__case__upper__a(chars__alphabet__case__upper__a___string),
  alphabet__case__upper__b(chars__alphabet__case__upper__b___string),
  alphabet__case__upper__c(chars__alphabet__case__upper__c___string),
  alphabet__case__upper__d(chars__alphabet__case__upper__d___string),
  alphabet__case__upper__e(chars__alphabet__case__upper__e___string),
  alphabet__case__upper__f(chars__alphabet__case__upper__f___string),
  alphabet__case__upper__g(chars__alphabet__case__upper__g___string),
  alphabet__case__upper__h(chars__alphabet__case__upper__h___string),
  alphabet__case__upper__i(chars__alphabet__case__upper__i___string),
  alphabet__case__upper__j(chars__alphabet__case__upper__j___string),
  alphabet__case__upper__k(chars__alphabet__case__upper__k___string),
  alphabet__case__upper__l(chars__alphabet__case__upper__l___string),
  alphabet__case__upper__m(chars__alphabet__case__upper__m___string),
  alphabet__case__upper__n(chars__alphabet__case__upper__n___string),
  alphabet__case__upper__o(chars__alphabet__case__upper__o___string),
  alphabet__case__upper__p(chars__alphabet__case__upper__p___string),
  alphabet__case__upper__q(chars__alphabet__case__upper__q___string),
  alphabet__case__upper__r(chars__alphabet__case__upper__r___string),
  alphabet__case__upper__s(chars__alphabet__case__upper__s___string),
  alphabet__case__upper__t(chars__alphabet__case__upper__t___string),
  alphabet__case__upper__u(chars__alphabet__case__upper__u___string),
  alphabet__case__upper__v(chars__alphabet__case__upper__v___string),
  alphabet__case__upper__w(chars__alphabet__case__upper__w___string),
  alphabet__case__upper__x(chars__alphabet__case__upper__x___string),
  alphabet__case__upper__y(chars__alphabet__case__upper__y___string),
  alphabet__case__upper__z(chars__alphabet__case__upper__z___string),
  //
  bracket__square__open(chars__bracket__square__open___string),
  slash__backward(chars__slash__backward___string),
  bracket__square__close(chars__bracket__square__close___string),
  caret(chars__caret___string),
  under_score(chars__underscore___string),
  quote__back(chars__quote__back___string),
  //
  alphabet__case__lower__a(chars__alphabet__case__lower__a___string),
  alphabet__case__lower__b(chars__alphabet__case__lower__b___string),
  alphabet__case__lower__c(chars__alphabet__case__lower__c___string),
  alphabet__case__lower__d(chars__alphabet__case__lower__d___string),
  alphabet__case__lower__e(chars__alphabet__case__lower__e___string),
  alphabet__case__lower__f(chars__alphabet__case__lower__f___string),
  alphabet__case__lower__g(chars__alphabet__case__lower__g___string),
  alphabet__case__lower__h(chars__alphabet__case__lower__h___string),
  alphabet__case__lower__i(chars__alphabet__case__lower__i___string),
  alphabet__case__lower__j(chars__alphabet__case__lower__j___string),
  alphabet__case__lower__k(chars__alphabet__case__lower__k___string),
  alphabet__case__lower__l(chars__alphabet__case__lower__l___string),
  alphabet__case__lower__m(chars__alphabet__case__lower__m___string),
  alphabet__case__lower__n(chars__alphabet__case__lower__n___string),
  alphabet__case__lower__o(chars__alphabet__case__lower__o___string),
  alphabet__case__lower__p(chars__alphabet__case__lower__p___string),
  alphabet__case__lower__q(chars__alphabet__case__lower__q___string),
  alphabet__case__lower__r(chars__alphabet__case__lower__r___string),
  alphabet__case__lower__s(chars__alphabet__case__lower__s___string),
  alphabet__case__lower__t(chars__alphabet__case__lower__t___string),
  alphabet__case__lower__u(chars__alphabet__case__lower__u___string),
  alphabet__case__lower__v(chars__alphabet__case__lower__v___string),
  alphabet__case__lower__w(chars__alphabet__case__lower__w___string),
  alphabet__case__lower__x(chars__alphabet__case__lower__x___string),
  alphabet__case__lower__y(chars__alphabet__case__lower__y___string),
  alphabet__case__lower__z(chars__alphabet__case__lower__z___string),
  //
  bracket__curly__open(chars__bracket__curly__open___string),
  pipe(chars__pipe___string),
  bracket__curly__close(chars__bracket__curly__close___string),
  tilde(chars__tilde___string),
  //
  delete___in_visible(empty___string) /* "DEL", "^?" */
  ;

  final string visual__representation;

  const CHAR__ASCII(this.visual__representation);
}
