part of "_.dart";

/*
 `char__abc` is a mere shortcut, for `ch__abc__text` */

const //
    char__line_feed = '\n',
    char__space = ' ',
    char__exclamation = '!',
    char__quote__double = '"',
    char__hash = '#',
    char__dollar = r'$',
    char__percent = '%',
    char__ampersand = '&',
    char__quote__single = '\'',
    char__bracket__round__open = '(',
    char__bracket__round__close = ')',
    char__asterisk = '*',
    char__plus = '+',
    char__comma = ',',
    char__dash = '-',
    char__minus = char__dash,
    char__dot = '.',
    char__point = char__dot,
    char__slash__forward = '/',
    char__number__zero = '0',
    char__number__one = '1',
    char__number__two = '2',
    char__number__three = '3',
    char__number__four = '4',
    char__number__five = '5',
    char__number__six = '6',
    char__number__seven = '7',
    char__number__eight = '8',
    char__number__nine = '9',
    char__colon = ':',
    char__colon__semi = ';',
    char__less_than = '<',
    char__bracket__angle__open = char__less_than,
    char__equal = '=',
    char__more_than = '>',
    char__bracket__angle__close = char__more_than,
    char__question = '?',
    char__at = '@',
    char__alphabet__case__upper__a = 'A',
    char__alphabet__case__upper__b = 'B',
    char__alphabet__case__upper__c = 'C',
    char__alphabet__case__upper__d = 'D',
    char__alphabet__case__upper__e = 'E',
    char__alphabet__case__upper__f = 'F',
    char__alphabet__case__upper__g = 'G',
    char__alphabet__case__upper__h = 'H',
    char__alphabet__case__upper__i = 'I',
    char__alphabet__case__upper__j = 'J',
    char__alphabet__case__upper__k = 'K',
    char__alphabet__case__upper__l = 'L',
    char__alphabet__case__upper__m = 'M',
    char__alphabet__case__upper__n = 'N',
    char__alphabet__case__upper__o = 'O',
    char__alphabet__case__upper__p = 'P',
    char__alphabet__case__upper__q = 'Q',
    char__alphabet__case__upper__r = 'R',
    char__alphabet__case__upper__s = 'S',
    char__alphabet__case__upper__t = 'T',
    char__alphabet__case__upper__u = 'U',
    char__alphabet__case__upper__v = 'V',
    char__alphabet__case__upper__w = 'W',
    char__alphabet__case__upper__x = 'X',
    char__alphabet__case__upper__y = 'Y',
    char__alphabet__case__upper__z = 'Z',
    char__bracket__square__open = '[',
    char__slash__backward = r'\',
    char__bracket__square__close = ']',
    char__caret = '^',
    char__underscore = '_',
    char__quote__back = '`',
    char__alphabet__case__lower__a = 'a',
    char__alphabet__a = char__alphabet__case__lower__a,
    char__alphabet__case__lower__b = 'b',
    char__alphabet__b = char__alphabet__case__lower__b,
    char__alphabet__case__lower__c = 'c',
    char__alphabet__c = char__alphabet__case__lower__c,
    char__alphabet__case__lower__d = 'd',
    char__alphabet__d = char__alphabet__case__lower__d,
    char__alphabet__case__lower__e = 'e',
    char__alphabet__e = char__alphabet__case__lower__e,
    char__alphabet__case__lower__f = 'f',
    char__alphabet__f = char__alphabet__case__lower__f,
    char__alphabet__case__lower__g = 'g',
    char__alphabet__g = char__alphabet__case__lower__g,
    char__alphabet__case__lower__h = 'h',
    char__alphabet__h = char__alphabet__case__lower__h,
    char__alphabet__case__lower__i = 'i',
    char__alphabet__i = char__alphabet__case__lower__i,
    char__alphabet__case__lower__j = 'j',
    char__alphabet__j = char__alphabet__case__lower__j,
    char__alphabet__case__lower__k = 'k',
    char__alphabet__k = char__alphabet__case__lower__k,
    char__alphabet__case__lower__l = 'l',
    char__alphabet__l = char__alphabet__case__lower__l,
    char__alphabet__case__lower__m = 'm',
    char__alphabet__m = char__alphabet__case__lower__m,
    char__alphabet__case__lower__n = 'n',
    char__alphabet__n = char__alphabet__case__lower__n,
    char__alphabet__case__lower__o = 'o',
    char__alphabet__o = char__alphabet__case__lower__o,
    char__alphabet__case__lower__p = 'p',
    char__alphabet__p = char__alphabet__case__lower__p,
    char__alphabet__case__lower__q = 'q',
    char__alphabet__q = char__alphabet__case__lower__q,
    char__alphabet__case__lower__r = 'r',
    char__alphabet__r = char__alphabet__case__lower__r,
    char__alphabet__case__lower__s = 's',
    char__alphabet__s = char__alphabet__case__lower__s,
    char__alphabet__case__lower__t = 't',
    char__alphabet__t = char__alphabet__case__lower__t,
    char__alphabet__case__lower__u = 'u',
    char__alphabet__u = char__alphabet__case__lower__u,
    char__alphabet__case__lower__v = 'v',
    char__alphabet__v = char__alphabet__case__lower__v,
    char__alphabet__case__lower__w = 'w',
    char__alphabet__w = char__alphabet__case__lower__w,
    char__alphabet__case__lower__x = 'x',
    char__alphabet__x = char__alphabet__case__lower__x,
    char__alphabet__case__lower__y = 'y',
    char__alphabet__y = char__alphabet__case__lower__y,
    char__alphabet__case__lower__z = 'z',
    char__alphabet__z = char__alphabet__case__lower__z,
    char__bracket__curly__open = '{',
    char__pipe = '|',
    char__bracket__curly__close = '}',
    char__tilde = '~',
//
    char__array /* `http://en.wikipedia.org/wiki/ASCII` */ = <string__raw>[
      empty__text /*'\0'*/ /* `NIL`, `null`, `^@` */, //
      empty__text /* `SOH`, `startOfHeading`, `^A` */,
      empty__text /* `STX`, `startOfText`, `^B` */,
      empty__text /* `ETX`, `endOfText`, `^C` */,
      empty__text /* `EOT`, `endOfTransmission`, `^D` */,
      empty__text /* `ENQ`, `enquiry`, `^E` */,
      empty__text /* `ACK`, `acknowledgement`, `^F` */, //
      empty__text /*'\a'*/ /* `BEL`, `bell`, `^G` */,
      '\b' /* `BS`, `backspace`, `^H` */,
      '\t' /* `HT`, `horizontalTab`, `^I` */,
      '\n' /* `LF`, `lineFeed`, `^J` */,
      '\v' /* `VT`, `verticalTab`, `^K` */,
      '\f' /* `FF`, `formFeed`, `^L` */,
      '\r' /* `CR`, `carriageReturn`, `^M` */, //
      empty__text /* `SO`, `shiftOut`, `^N` */,
      empty__text /* `SI`, `shiftIn`, `^O` */,
      empty__text /* `DLE`, `dataLinkEscape`, `^P` */,
      empty__text /* `DC1`, `deviceControlOne`, `^Q` */,
      empty__text /* `DC2`, `deviceControlTwo`, `^R` */,
      empty__text /* `DC3`, `deviceControlThree`, `^S` */,
      empty__text /* `DC4`, `deviceControlFour`, `^T` */,
      empty__text /* `NAK`, `negativeAcknowledgement`, `^U` */,
      empty__text /* `SYN`, `synchronousIdle`, `^V` */,
      empty__text /* `ETB`, `endOfTransmissionBlock`, `^W` */,
      empty__text /* `CAN`, `cancel`, `^X` */,
      empty__text /* `EM`, `endOfMedium`, `^Y` */,
      empty__text /* `SUB`, `substitute`, `^Z` */, //
      empty__text /*'\e'*/ /* `ESC`, `escape`, `^[` */, //
      empty__text /* `FS`, `fileSeparator`, `^\` */,
      empty__text /* `GS`, `groupSeparator`, `^]` */,
      empty__text /* `RS`, `recordSeparator`, `^^` */,
      empty__text /* `US`, `unitSeparator`, `^_` */, //
      char__space,
      '!',
      '"',
      '#',
      '\$',
      '%',
      '&',
      '\'',
      '(',
      ')',
      '*',
      '+',
      ',',
      '-',
      '.',
      '/', //
      '0',
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      ':',
      ';',
      '<',
      '=',
      '>',
      '?',
      '@', //
      'A',
      'B',
      'C',
      'D',
      'E',
      'F',
      'G',
      'H',
      'I',
      'J',
      'K',
      'L',
      'M',
      'N',
      'O',
      'P',
      'Q',
      'R',
      'S',
      'T',
      'U',
      'V',
      'W',
      'X',
      'Y',
      'Z', //
      '[',
      '\\',
      ']',
      '^',
      '_',
      '`', //
      'a',
      'b',
      'c',
      'd',
      'e',
      'f',
      'g',
      'h',
      'i',
      'j',
      'k',
      'l',
      'm',
      'n',
      'o',
      'p',
      'q',
      'r',
      's',
      't',
      'u',
      'v',
      'w',
      'x',
      'y',
      'z', //
      '{',
      '|',
      '}',
      '~', //
      empty__text /* `DEL`, `delete`, `^?` */
    ];
