part of "_.dart";

enum CHAR__ASCII /*
  web://org.wikipedia/ASCII */ {
  null___in_visible(empty___string) /* "NIL", "^@" */,
  start_of_heading___in_visible(empty___string) /* "SOH", "^A" */,
  start_of_text___in_visible(empty___string) /* "STX", "^B" */,
  end_of_text___in_visible(empty___string) /* "ETX", "^C" */,
  end_of_transmission___in_visible(empty___string) /* "EOT", "^D" */,
  enquiry___in_visible(empty___string) /* "ENQ", "^E" */,
  acknowledgement___in_visible(empty___string) /* "ACK", "^F" */,
  bell___in_visible(empty___string) /* "BEL", "^G" */,
  backspace___in_visible(empty___string) /* "BS", "^H" */,
  horizontal_tab___in_visible(empty___string) /* "HT", "^I" */,
  //
  line_feed___in_visible(base__chars__line_feed___string) /* "LF", "^J" */,
  //
  vertical_tab___in_visible(empty___string) /* "VT", "^K" */,
  form_feed___in_visible(empty___string) /* "FF", "^L" */,
  carriage_return___in_visible(empty___string) /* "CR", "^M" */,
  shift_out___in_visible(empty___string) /* "SO", "^N" */,
  shift_in___in_visible(empty___string) /* "SI", "^O" */,
  data_link_escape___in_visible(empty___string) /* "DLE", "^P" */,
  device_control_one___in_visible(empty___string) /* "DC1", "^Q" */,
  device_control_two___in_visible(empty___string) /* "DC2", "^R" */,
  device_control_three___in_visible(empty___string) /* "DC3", "^S" */,
  device_control_four___in_visible(empty___string) /* "DC4", "^T" */,
  negative_acknowledgement___in_visible(empty___string) /* "NAK", "^U" */,
  synchronous_idle___in_visible(empty___string) /* "SYN", "^V" */,
  end_of_transmission_block___in_visible(empty___string) /* "ETB", "^W" */,
  cancel___in_visible(empty___string) /* "CAN", "^X" */,
  end_of_medium___in_visible(empty___string) /* "EM", "^Y" */,
  substitute___in_visible(empty___string) /* "SUB", "^Z" */,
  escape___in_visible(empty___string) /* "ESC", "^[" */,
  file_separator___in_visible(empty___string) /* "FS", "^\" */,
  group_separator___in_visible(empty___string) /* "GS", "^]" */,
  record_separator___in_visible(empty___string) /* "RS", "^^" */,
  unit_separator___in_visible(empty___string) /* "US", "^_" */,
  //
  space(base__chars__space___string),
  exclamation(base__chars__exclamation___string),
  quote__double(base__chars__quote__double___string),
  hash(base__chars__hash___string),
  dollar(base__chars__dollar___string),
  percent(base__chars__percent___string),
  ampersand(base__chars__ampersand___string),
  quote__single(base__chars__quote__single___string),
  bracket__round__open(base__chars__bracket__round__open___string),
  bracket__round__close(base__chars__bracket__round__close___string),
  asterisk(base__chars__asterisk___string),
  plus(base__chars__plus___string),
  comma(base__chars__comma___string),
  dash(base__chars__dash___string),
  dot(base__chars__dot___string),
  slash__forward(base__chars__slash__forward___string),
  //
  number__zero(base__chars__number__zero___string),
  number__one(base__chars__number__one___string),
  number__two(base__chars__number__two___string),
  number__three(base__chars__number__three___string),
  number__four(base__chars__number__four___string),
  number__five(base__chars__number__five___string),
  number__six(base__chars__number__six___string),
  number__seven(base__chars__number__seven___string),
  number__eight(base__chars__number__eight___string),
  number__nine(base__chars__number__nine___string),
  //
  colon(base__chars__colon___string),
  colon__semi(base__chars__colon__semi___string),
  bracket__angle__open(base__chars__less_than___string),
  equal(base__chars__equal___string),
  bracket__angle__close(base__chars__more_than___string),
  question(base__chars__question___string),
  at(base__chars__at___string),
  //
  alphabet__case__upper__a(base__chars__alphabet__case__upper__a___string),
  alphabet__case__upper__b(base__chars__alphabet__case__upper__b___string),
  alphabet__case__upper__c(base__chars__alphabet__case__upper__c___string),
  alphabet__case__upper__d(base__chars__alphabet__case__upper__d___string),
  alphabet__case__upper__e(base__chars__alphabet__case__upper__e___string),
  alphabet__case__upper__f(base__chars__alphabet__case__upper__f___string),
  alphabet__case__upper__g(base__chars__alphabet__case__upper__g___string),
  alphabet__case__upper__h(base__chars__alphabet__case__upper__h___string),
  alphabet__case__upper__i(base__chars__alphabet__case__upper__i___string),
  alphabet__case__upper__j(base__chars__alphabet__case__upper__j___string),
  alphabet__case__upper__k(base__chars__alphabet__case__upper__k___string),
  alphabet__case__upper__l(base__chars__alphabet__case__upper__l___string),
  alphabet__case__upper__m(base__chars__alphabet__case__upper__m___string),
  alphabet__case__upper__n(base__chars__alphabet__case__upper__n___string),
  alphabet__case__upper__o(base__chars__alphabet__case__upper__o___string),
  alphabet__case__upper__p(base__chars__alphabet__case__upper__p___string),
  alphabet__case__upper__q(base__chars__alphabet__case__upper__q___string),
  alphabet__case__upper__r(base__chars__alphabet__case__upper__r___string),
  alphabet__case__upper__s(base__chars__alphabet__case__upper__s___string),
  alphabet__case__upper__t(base__chars__alphabet__case__upper__t___string),
  alphabet__case__upper__u(base__chars__alphabet__case__upper__u___string),
  alphabet__case__upper__v(base__chars__alphabet__case__upper__v___string),
  alphabet__case__upper__w(base__chars__alphabet__case__upper__w___string),
  alphabet__case__upper__x(base__chars__alphabet__case__upper__x___string),
  alphabet__case__upper__y(base__chars__alphabet__case__upper__y___string),
  alphabet__case__upper__z(base__chars__alphabet__case__upper__z___string),
  //
  bracket__square__open(base__chars__bracket__square__open___string),
  slash__backward(base__chars__slash__backward___string),
  bracket__square__close(base__chars__bracket__square__close___string),
  caret(base__chars__caret___string),
  under_score(base__chars__underscore___string),
  quote__back(base__chars__quote__back___string),
  //
  alphabet__case__lower__a(base__chars__alphabet__case__lower__a___string),
  alphabet__case__lower__b(base__chars__alphabet__case__lower__b___string),
  alphabet__case__lower__c(base__chars__alphabet__case__lower__c___string),
  alphabet__case__lower__d(base__chars__alphabet__case__lower__d___string),
  alphabet__case__lower__e(base__chars__alphabet__case__lower__e___string),
  alphabet__case__lower__f(base__chars__alphabet__case__lower__f___string),
  alphabet__case__lower__g(base__chars__alphabet__case__lower__g___string),
  alphabet__case__lower__h(base__chars__alphabet__case__lower__h___string),
  alphabet__case__lower__i(base__chars__alphabet__case__lower__i___string),
  alphabet__case__lower__j(base__chars__alphabet__case__lower__j___string),
  alphabet__case__lower__k(base__chars__alphabet__case__lower__k___string),
  alphabet__case__lower__l(base__chars__alphabet__case__lower__l___string),
  alphabet__case__lower__m(base__chars__alphabet__case__lower__m___string),
  alphabet__case__lower__n(base__chars__alphabet__case__lower__n___string),
  alphabet__case__lower__o(base__chars__alphabet__case__lower__o___string),
  alphabet__case__lower__p(base__chars__alphabet__case__lower__p___string),
  alphabet__case__lower__q(base__chars__alphabet__case__lower__q___string),
  alphabet__case__lower__r(base__chars__alphabet__case__lower__r___string),
  alphabet__case__lower__s(base__chars__alphabet__case__lower__s___string),
  alphabet__case__lower__t(base__chars__alphabet__case__lower__t___string),
  alphabet__case__lower__u(base__chars__alphabet__case__lower__u___string),
  alphabet__case__lower__v(base__chars__alphabet__case__lower__v___string),
  alphabet__case__lower__w(base__chars__alphabet__case__lower__w___string),
  alphabet__case__lower__x(base__chars__alphabet__case__lower__x___string),
  alphabet__case__lower__y(base__chars__alphabet__case__lower__y___string),
  alphabet__case__lower__z(base__chars__alphabet__case__lower__z___string),
  //
  bracket__curly__open(base__chars__bracket__curly__open___string),
  pipe(base__chars__pipe___string),
  bracket__curly__close(base__chars__bracket__curly__close___string),
  tilde(base__chars__tilde___string),
  //
  delete___in_visible(empty___string) /* "DEL", "^?" */
  ;

  final string visual__representation;

  const CHAR__ASCII(this.visual__representation);
}
